version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - cluster.name=contextElasticSearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  unomi:
    image: unomi
    container_name: unomi
    environment:
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
    ports:
      - 8181:8181
      - 9443:9443
    links:
      - elasticsearch
